server:
  port: 7777
#spring:
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql:///:3306/web
#  username: root # ???
#  password: 123456 # ??

spring:
  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///web?useSSL=false
      username: root
      password: 123456
    ds2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:localhost:3307/web
      username: root
      password: 123456
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true